# Site setting
title: Hello, world! I'm Milai
description: 没事，写点东西，记录一下，总能沉淀一些东西。
permalink: ':title/'
baseurl: "" 
url: "" 

future: true
# Author Settings
author: 米来Milai # add your name
author-img: milai.jpg # add your photo
about-author: 
social-cnblog: weilai1917 # add your Twitter handle
social-github: weilai1917 # add your Github handle
social-jianshu: bb0bded1fafa

# Disqus
# discus-identifier:  # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins: [jekyll-sitemap, jekyll-paginate, jemoji] 

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
